export * as log from "https://deno.land/std@0.211.0/log/mod.ts";
export { format } from "https://deno.land/std@0.176.0/node/util.ts";
export * as colors from "https://deno.land/std@0.173.0/fmt/colors.ts";
export * as conversions from "https://deno.land/std@0.172.0/streams/conversion.ts";
export { default as levenshtein } from "https://deno.land/x/levenshtein@v1.0.1/mod.ts";
export { stderr, stdout } from "https://deno.land/std@0.173.0/node/process.ts";
export * as path from "https://deno.land/std@0.167.0/path/mod.ts";
export { default as figlet_factory } from "https://x.nest.land/deno-figlet@0.0.5/deps/factory.js";
export { default as figlet_serializer } from "https://x.nest.land/deno-figlet@0.0.5/deps/serializer.js";
export { emphasize } from "https://esm.sh/emphasize@6.0.0/lib/core";
export { default as jsonSyntaxDefinition } from "https://esm.sh/highlight.js@11.8.0/lib/languages/json";
export type { LanguageFn as HighlightSyntax } from "https://esm.sh/highlight.js@11.6.0";
