export * as log from "https://deno.land/std@0.223.0/log/mod.ts";
export { sprintf } from "https://deno.land/std@0.223.0/fmt/printf.ts";
export * as colors from "https://deno.land/std@0.223.0/fmt/colors.ts";
export * as io from "https://deno.land/std@0.223.0/io/mod.ts";
export { default as levenshtein } from "https://deno.land/x/levenshtein@v1.0.1/mod.ts";
export * as path from "https://deno.land/std@0.223.0/path/mod.ts";
export { default as figlet_factory } from "https://x.nest.land/deno-figlet@0.0.5/deps/factory.js";
export { default as figlet_serializer } from "https://x.nest.land/deno-figlet@0.0.5/deps/serializer.js";
export { createEmphasize } from "npm:emphasize@7.0.0";
export { default as jsonSyntaxDefinition } from "https://unpkg.com/@highlightjs/cdn-assets@11.9.0/es/languages/json.min.js";
export type { LanguageFn as HighlightSyntax } from "https://esm.sh/highlight.js@11.9.0/";
export { writeAll } from "https://deno.land/std@0.223.0/io/write_all.ts";
